name: find_my_tennis

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.5
  firebase_auth: ^0.16.0
  permission_handler: ^5.0.0+hotfix.5
  rxdart: 0.23.1
  flutter_bloc: ^4.0.0
  bloc: ^4.0.0
  equatable: ^1.1.1
  provider: ^4.0.5+1

#  maps
  google_maps_flutter: ^0.5.27+1
  google_maps_webservice: ^0.0.16
  flutter_google_places: 0.2.4
  geoflutterfire: ^2.1.0
  location: ^3.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/